### ISSUE TITLE
SWC Beta Testnet Checklist

### ISSUE THREAD

**Issue by qizhou** [ethstorage/pm#149]
- [ ] #150 Make sure token symbol is QKC (can the symbol be configurable?)
- [x] #151 
- [ ] Tests
  - [ ] CircleCI tests https://github.com/ethstorage/optimism/issues/113 https://github.com/ethstorage/optimism/issues/112 https://github.com/ethstorage/optimism/issues/111
  - [ ] E2E tests https://github.com/ethstorage/optimism/issues/100
  - [ ] Airdrop tests
- [x] #154
- [x] #153
- [x] #155
- [x] Bridge
- [x] EthStorage L3
- [ ] Scalar update https://github.com/ethstorage/optimism/issues/93
- [ ] Docs https://github.com/ethstorage/swc-doc
- [x] Blog setup: reuse medium
- [ ] #157
- [ ] #162
